export default [
  {id: 'TR', country: 'Turkey', dial_code: '+90', region: 'ME-AS' },
  {id: 'BH', country: 'Bahrain', dial_code: '+973', region: 'ME-AS' },
  {id: 'KW', country: 'Kuwait', dial_code: '+965', region: 'ME-AS' },
  {id: 'OM', country: 'Oman', dial_code: '+968', region: 'ME-AS' },
  {id: 'QA', country: 'Qatar', dial_code: '+974', region: 'ME-AS' },
  {id: 'SA', country: 'Saudi Arabia', dial_code: '+966', region: 'ME-AS' },
  {id: 'AE', country: 'United Arab Emirates', dial_code: '+971', region: 'ME-AS' },
  {id: 'YE', country: 'Yemen', dial_code: '+967', region: 'ME-AS' },
  {id: 'AM', country: 'Armenia', dial_code: '+374', region: 'ME-AS' },
  {id: 'AZ', country: 'Azerbaijan', dial_code: '+994', region: 'ME-AS' },
  {id: 'GE', country: 'Georgia', dial_code: '+995', region: 'ME-AS' },
  {id: 'IQ', country: 'Iraq', dial_code: '+964', region: 'ME-AS' },
  {id: 'IL', country: 'Israel', dial_code: '+972', region: 'ME-AS' },
  {id: 'JO', country: 'Jordan', dial_code: '+962', region: 'ME-AS' },
  {id: 'LB', country: 'Lebanon', dial_code: '+961', region: 'ME-AS' },
  {id: 'PS', country: 'Palestine', dial_code: '+970', region: 'ME-AS' },
  {id: 'SY', country: 'Syria', dial_code: '+963', region: 'ME-AS' },
  {id: 'IR', country: 'Iran', dial_code: '+98', region: 'ME-AS' },
  {id: 'CY', country: 'Cyprus', dial_code: '+357', region: 'ME-AS' },
]
