export default [
  {id: 'AU', country: 'Australia', dial_code: '+672', region: 'OC-AU' },
  {id: 'NZ', country: 'New Zealand', dial_code: '+64', region: 'OC-AU' },
  {id: 'FJ', country: 'Fiji', dial_code: '+679', region: 'OC-AU' },
  {id: 'PG', country: 'Papua New Guinea', dial_code: '+675', region: 'OC-AU' },
  {id: 'SB', country: 'Solomon Islands', dial_code: '+677', region: 'OC-AU' },
  {id: 'VU', country: 'Vanuatu', dial_code: '+678', region: 'OC-AU' },
  {id: 'FM', country: 'Federated States of Micronesia', dial_code: '+691', region: 'OC-AU' },
  {id: 'KI', country: 'Kiribati', dial_code: '+686', region: 'OC-AU' },
  {id: 'MH', country: 'Marshall Islands', dial_code: '+692', region: 'OC-AU' },
  {id: 'NR', country: 'Nauru', dial_code: '+674', region: 'OC-AU' },
  {id: 'PW', country: 'Palau', dial_code: '+680', region: 'OC-AU' },
  {id: 'WS', country: 'Samoa', dial_code: '+685', region: 'OC-AU' },
  {id: 'SM', country: 'Tonga', dial_code: '+676', region: 'OC-AU' },
  {id: 'TV', country: 'Tuvalu', dial_code: '+688', region: 'OC-AU' },
]
