export default [
  //East Africa
  {id: 'SD', country: 'Sudan', dial_code: '+249', region: 'SS-AF' },
  {id: 'TZ', country: 'Tanzania', dial_code: '+255', region: 'SS-AF' },
  {id: 'KE', country: 'Kenya', dial_code: '+254', region: 'SS-AF' },
  {id: 'UG', country: 'Uganda', dial_code: '+256', region: 'SS-AF' },
  {id: 'RW', country: 'Rwanda', dial_code: '+250', region: 'SS-AF' },
  {id: 'BI', country: 'Burundi', dial_code: '+257', region: 'SS-AF' },
  {id: 'SS', country: 'South Sudan', dial_code: '+211', region: 'SS-AF' },
  {id: 'DJ', country: 'Djibouti', dial_code: '+253', region: 'SS-AF' },
  {id: 'ER', country: 'Eritrea', dial_code: '+291', region: 'SS-AF' },
  {id: 'ET', country: 'Ethiopia', dial_code: '+251', region: 'SS-AF' },
  {id: 'SO', country: 'Somalia', dial_code: '+252', region: 'SS-AF' },
  //Southeast Africa
  {id: 'KM', country: 'Comoros', dial_code: '+269', region: 'SS-AF' },
  {id: 'MU', country: 'Mauritius', dial_code: '+230', region: 'SS-AF' },
  {id: 'SC', country: 'Seychelles', dial_code: '+248', region: 'SS-AF' },
  {id: 'RE', country: 'Réunion', dial_code: '+262', region: 'SS-AF' },
  {id: 'YT', country: 'Mayotte', dial_code: '+262 269', region: 'SS-AF' },
  {id: 'MZ', country: 'Mozambique', dial_code: '+258', region: 'SS-AF' },
  {id: 'MG', country: 'Madagascar', dial_code: '+261', region: 'SS-AF' },
  {id: 'MW', country: 'Malawi', dial_code: '+265', region: 'SS-AF' },
  {id: 'ZM', country: 'Zambia', dial_code: '+260', region: 'SS-AF' },
  {id: 'ZW', country: 'Zimbabwe', dial_code: '+263', region: 'SS-AF' },
  //Southern Africa
  {id: 'BW', country: 'Botswana', dial_code: '+267', region: 'SS-AF' },
  {id: 'SZ', country: 'Eswatini', dial_code: '+268', region: 'SS-AF' },
  {id: 'LS', country: 'Lesotho', dial_code: '+266', region: 'SS-AF' },
  {id: 'NA', country: 'Namibia', dial_code: '+264', region: 'SS-AF' },
  {id: 'ZA', country: 'South Africa', dial_code: '+27', region: 'SS-AF' },
  //Central/Middle Africa
  {id: 'AO', country: 'Angola', dial_code: '+244', region: 'SS-AF' },
  {id: 'CM', country: 'Cameroon', dial_code: '+237', region: 'SS-AF' },
  {id: 'CF', country: 'Central African Republic', dial_code: '+236', region: 'SS-AF' },
  {id: 'TD', country: 'Chad', dial_code: '+235', region: 'SS-AF' },
  {id: 'CD', country: 'DR Congo', dial_code: '+242', region: 'SS-AF' },
  {id: 'CG', country: 'Republic of the Congo', dial_code: '+242', region: 'SS-AF' },
  {id: 'GQ', country: 'Equatorial Guinea', dial_code: '+240', region: 'SS-AF' },
  {id: 'GA', country: 'Gabon', dial_code: '+241', region: 'SS-AF' },
  {id: 'ST', country: 'São Tomé and Príncipe', dial_code: '+239', region: 'SS-AF' },
  {id: 'RW', country: 'Rwanda', dial_code: '+250', region: 'SS-AF' },
  {id: 'BI', country: 'Burundi', dial_code: '+257', region: 'SS-AF' },
  //West Africa
  {id: 'BJ', country: 'Benin', dial_code: '+229', region: 'SS-AF' },
  {id: 'BF', country: 'Burkina Faso', dial_code: '+226', region: 'SS-AF' },
  {id: 'CV', country: 'Cabo Verde', dial_code: '+238', region: 'SS-AF' },
  {id: 'CI', country: 'Ivory Coast', dial_code: '+225', region: 'SS-AF' },
  {id: 'GM', country: 'The Gambia', dial_code: '+220', region: 'SS-AF' },
  {id: 'GH', country: 'Ghana', dial_code: '+233', region: 'SS-AF' },
  {id: 'GN', country: 'Guinea', dial_code: '+224', region: 'SS-AF' },
  {id: 'GW', country: 'Guinea-Bissau', dial_code: '+245', region: 'SS-AF' },
  {id: 'LR', country: 'Liberia', dial_code: '+231', region: 'SS-AF' },
  {id: 'ML', country: 'Mali', dial_code: '+223', region: 'SS-AF' },
  {id: 'MR', country: 'Mauritania', dial_code: '+222', region: 'SS-AF' },
  {id: 'NE', country: 'Niger', dial_code: '+227', region: 'SS-AF' },
  {id: 'NG', country: 'Nigeria', dial_code: '+234', region: 'SS-AF' },
  {id: 'SN', country: 'Senegal', dial_code: '+221', region: 'SS-AF' },
  {id: 'SL', country: 'Sierra Leone', dial_code: '+232', region: 'SS-AF' },
  {id: 'TG', country: 'Togo', dial_code: '+228', region: 'SS-AF' },
]
